# Generated by Django 3.0.5 on 2020-04-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('uRollNo', models.IntegerField(verbose_name='University Roll no:')),
            ],
        ),
    ]
